---
# VyOS Configuration Playbook
# Applies configuration to all VyOS routers in inventory

- hosts: vyos_routers
  gather_facts: false
  
  tasks:
    - import_role:
        name: bootstrap
      tags: ['bootstrap', 'system']

    - import_role:
        name: network
      tags: ['network', 'interfaces']

    - import_role:
        name: firewall
      tags: ['firewall']

    - import_role:
        name: nat
      tags: ['nat']

    - import_role:
        name: services
      tags: ['services', 'dns']
    
    - name: Save configuration
      vyos.vyos.vyos_config:
        save: true
      tags: ['always']
